version: "2.1"
services:
  blocky:
    restart: always
    image: spx01/blocky
    # container_name: blocky
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp" # Prometheus stats (if enabled).
    environment:
      - TZ=Europe/Berlin
    volumes:
      # config file
      - ./config.yml:/app/config.yml
      # write query logs in this volume
      # - queryLogs:/logs
      # put your custom white and blacklists in these directories
      # - ./blacklists:/app/blacklists/
      # - ./whitelists:/app/whitelists/
